### ISSUE TITLE
server_ipv6_addr need to be added to requires_one_of for a10_slb_server.py to allow IPv6 servers

### ISSUE THREAD

**Issue by glassrye** [a10networks/a10-ansible#13]
What is the proper syntax for slb server and IPv6 address? 'host' gives and error about invalid IPv4 address which makes sense, but both 'ipv6' and 'server_ipv6_addr' give a validation error.

Thank you.

Also, the email in the README is rejected by the server.

Debug info below along with the play:
```
TASK [Create a10 server server1.v6] *******************************************************************************************************************************************************
task path: /home/vagrant/ANSIBLE/ansible-experiments/media/SV5/create-nodes.yml:142
Using module file /home/vagrant/ANSIBLE/a10-ansible/a10_ansible/library/a10_slb_server.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1524559431.28-188996405751674 `" && echo ansible-tmp-1524559431.28-188996405751674="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1524559431.28-188996405751674 `" ) && sleep 0'
<127.0.0.1> PUT /home/vagrant/.ansible/tmp/ansible-local-26673ruwHrU/tmpD4T4ph TO /home/vagrant/.ansible/tmp/ansible-tmp-1524559431.28-188996405751674/a10_slb_server.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1524559431.28-188996405751674/ /home/vagrant/.ansible/tmp/ansible-tmp-1524559431.28-188996405751674/a10_slb_server.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/vagrant/ANSIBLE/.ansible/bin/python2 /home/vagrant/.ansible/tmp/ansible-tmp-1524559431.28-188996405751674/a10_slb_server.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1524559431.28-188996405751674/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "a10_host": "********_dev",
            "a10_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "a10_username": "admin",
            "action": "enable",
            "alternate_server": null,
            "conn_limit": null,
            "conn_resume": null,
            "extended_stats": null,
            "external_ip": null,
            "fqdn_name": null,
            "health_check": null,
            "health_check_disable": null,
            "host": null,
            "ipv6": null,
            "name": "server1.v6",
            "no_logging": null,
            "port_list": [
                {
                    "health-check": "server_host_check_6001",
                    "port-number": 80,
                    "protocol": "tcp"
                },
                {
                    "health-check": "server_host_check_6001",
                    "port-number": 443,
                    "protocol": "tcp"
                }
            ],
            "sampling_enable": null,
            "server_ipv6_addr": "<REDACTED>:e002:2004::102",
            "slow_start": null,
            "spoofing_cache": null,
            "state": "present",
            "stats_data_action": null,
            "template_server": "ALL",
            "user_tag": null,
            "uuid": null,
            "weight": null
        }
    },
    "message": "",
    "messages": "Validation failure",
    "msg": "",
    "original_message": ""
}
    to retry, use: --limit @/home/vagrant/ANSIBLE/ansible-experiments/media/SV5/create-nodes.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************
localhost                  : ok=8    changed=8    unreachable=0    failed=1
```

Here is the play:
```
  - name: Create a10 server server1.v6
    a10_slb_server:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      name: "server1.v6"
      server_ipv6_addr: "<REDACTED>:e002:2004::102"
      action: enable
      state: present
      template_server: "ALL"
      port_list:
        - port-number: 80
          protocol: tcp
          health-check: server_host_check_6001
        - port-number: 443
          protocol: tcp
          health-check: server_host_check_6001
```
