### ISSUE TITLE
health monitor method should be of type 'dict' and not 'str'

### ISSUE THREAD

**Issue by glassrye** [a10networks/a10-ansible#14]
a10_health_monitor.py
this section: 
```
   method=dict(
            type='str'
        ),
```
should be:
```
   method=dict(
            type='dict'
        ),
```

Which allows access to the http method (and other types) and subsequently a play like this will work
```
- name: Create A10 Health Checks
  a10_health_monitor:
    a10_host: "{{ a10_host }}"
    a10_username: "{{ a10_username }}"
    a10_password: "{{ a10_password }}"
    state: present
    name: "server_check_6001"
    override_port: "6001"
    method:
      http:
        http: "1"
        http-port: "80"
        http-expect: "1"
        http-text: "OK"
        http-maintenance-code: "503,404"
        http-url: "1"
        url-type: "GET"
        url-path: "/images/test/OK.html"
```
