### ISSUE TITLE
How do you use a10_file_glm_license ?

### ISSUE THREAD

**Issue by GoldenMouse** [a10networks/a10-ansible#70]
How do I use a10_file_glm_license module.
I keep getting values incorrect for file_handle variable. 
I've tried 

```
file_handle: file_handle: "{{lookup('file', 'path/to/file')}}"
```
and
```
file_handle: "/path/to/file"
```

but it doesn't work.

**Comment by hthompson6** [comment]
Instead of using the license file, use the (License) Entitlement Token.

This can be found by the following steps:
- Navigate glm.a10networks.com
- Click on the "Organizations" tab in the top right hand corner
- Choose the organization where the license for the device was created
- Click the "Licenses" tab on the left side bar
- Click on the license name
- There under the info tab you'll find the "Entitlement Token" section
- Copy this token and replace "EXAMPLE_TOKEN" with it in the following playbook below

```yaml
- name: Add a glm license example
  connection: local
  hosts: all
  tasks:
  - name: Authenticate via token
    a10_glm:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_protocol: "{{ a10_protocol }}"
      a10_port: "{{ a10_port }}"
      token: "EXAMPLE_TOKEN"
      use_mgmt_port: 0
  - name: Request license
    a10_glm:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_protocol: "{{ a10_protocol }}"
      a10_port: "{{ a10_port }}"
      use_mgmt_port: 0
      send:
        license-request: 1
```

- Set `use_mgmt_port` to `1` if the vThunder has only one network interface.
  - You can also test whether or not you need this by ssh'ing into the device and pinging `8.8.8.8` with the commands: `ping 8.8.8.8` and then `ping 8.8.8.8 use-mgmt-port` if the first command returns `Network unreachable`
